# Configuration for Feature Engineering and Model Training Pipeline

# Input data configuration
data:
  input_file: "../data/example_train_dataset.csv"

# Feature extraction configuration
features:
  eplet:
    dqa_to_sequence_file: "../data/jsons/dqa_to_seq.json"
    dqb_to_sequence_file: "../data/jsons/dqb_to_seq.json"
    allele_descriptions_file: "../data/jsons/all_eplets.json"
    output_file: "../output/features/eplet_features.csv"

  biological:
    ems_distances_file: "../data/jsons/ems_distances.json"
    pam_distances_file: "../data/jsons/pam_distances.json"
    g12_values_file: "../data/jsons/g12_classifications.json"
    features_to_extract: ["PAM", "EMS", "G12"]
    output_file: "../output/features/biological_features.csv"

  combined:
    output_file: "../output/features/combined_features.csv"

# Model configuration
model:
  type: "logreg"  # Options: "lgbm", "xgb", "logreg"
  k_folds: 5
  save: true
  path: "../output/models_saved/model.pkl"

# Evaluation configuration
evaluation:
  roc_plot_path: "../output/plots/train_roc_curve.png"